config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { minimum: 3, maximum: 100 }

  # Exemple : Created on today
  scope :created_on, ->(date) { where(created_at: date.all_day).order(created_at: :asc) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :username,  presence: true,
                        uniqueness: { case_sensitive: false },
                        length: { minimum: 3, maximum: 15 }
  has_many :messages, dependent: :destroy
  has_secure_password

  # Exemple : online
  scope :online, -> { where(online: true).order(username: :asc) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :user_online?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_online?
    current_user&.online || false
  end

  def require_user
    return if user_online?

    redirect_to login_path
  end
end

app/controllers/chatroom_controller.rb
# frozen_string_literal: true

class ChatroomController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.created_on(Time.zone.today)
    @users = User.online
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    return unless message.save

    ActionCable.server.broadcast 'chatroom_channel', { msg: msg_render(message) }
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def msg_render(message)
    render(partial: 'message', locals: { message: })
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]

  def new; end

  def create # rubocop:disable Metrics/MethodLength
    user = User.find_by(username: params[:session][:username])
    if valid_user?(user, params[:session][:password])
      if user.online
        login_already(user)
      else
        user.online = true
        user.save ? login_successful(user) : login_failed
      end
    else
      login_error
    end
  end

  def destroy
    user = current_user
    return unless user

    user.online = false
    return unless user.save

    session[:user_id] = nil
    flash[:success] = 'Logged out successfully!'
    update_users_list
    redirect_to login_path
  end

  private

  def valid_user?(user, password)
    user&.authenticate(password)
  end

  def login_successful(user)
    session[:user_id] = user.id
    flash[:success] = 'Logged in successfully!'
    update_users_list
    redirect_to root_path
  end

  def login_failed
    flash[:error] = 'Logged in not successfully!'
    redirect_to login_path
  end

  def login_error
    flash[:error] = 'Invalid credentials!'
    redirect_to login_path
  end

  def login_already(user)
    session[:user_id] = user.id
    flash[:error] = 'You are already logged in!'
    redirect_to root_path
  end

  def logged_in_redirect
    return unless user_online?

    flash[:error] = 'You are already logged in!'
    redirect_to root_path
  end

  def update_users_list
    @users = User.online
    ActionCable.server.broadcast 'users_list_channel', { users: @users }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular orange rocketchat icon"></i>
  Say something
</h2>
<div class="ui grid fluid container">
  <div class="twelve wide column">
    <div class="ui fluid card chatbox">
      <div class="content" id="messages">
        <%= render @messages %>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: "Enter a message...", autocomplete: "on" %>
              <%= f.button '<i class="orange large fitted edit icon"></i>'.html_safe, class: "ui basic icon button", id: "message_button" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid card chatbox">
      <div class="content">
        <div class="ui inverted vertical fluid menu" id="user_list">
          <% @users.each do |user| %>
            <div class="item">
              <%= user.username %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="ui container">
  <% flash.each do |type, msg| %>
    <div class="ui <%= type %> message" role="alert"><i class="close icon"></i>
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui segment inverted menu">
  <% if user_online? %>
    <div class="left menu">
      <%= link_to '<i class="rocketchat icon"></i> Chat Room'.html_safe, root_path, class: "ui primary button" %>
    </div>
  <% end %>
  <div class="right menu">
    <div class="ui primary buttons">
      <% if user_online? %>
         <div class="ui button"><%= current_user.username %></div>
      <% else %>
        <div class="ui button">Account</div>
      <% end %>
      <div class="ui floating dropdown icon button">
        <i class="dropdown icon"></i>
        <div class="menu">
          <% if user_online? %>
            <%= link_to '<i class="sign-out icon"></i> Logout'.html_safe, logout_path, class: "item", method: :delete %>
          <% else %>
            <%= link_to '<i class="sign-in icon"></i> Login'.html_safe, login_path, class: "item" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="ui fluid container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="ui feed">
    <div class="ui orange image label"><i class=" user outline icon"></i><%= message.user.username %></div> <%= message.body %>
</div>